# Generated by Django 4.2.7 on 2023-11-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boooks',
            name='rating',
            field=models.IntegerField(max_length=125, null=True),
        ),
    ]
