# Generated by Django 4.2.7 on 2023-11-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_boooks_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='boooks',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
